In [6]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [5]:
# クォータニオンからオイラー角への変換例
quaternion = [0, 0, 0, 1]  # 例: [x, y, z, w]
rotation = R.from_quat(quaternion)
euler = rotation.as_euler('xyz', degrees=True)  # 'xyz' または 'zyx' などの順序、degrees=True で度数法に

# オイラー角からクォータニオンへの変換例
euler_angles = [45, 45, 45]  # 例: [ロール, ピッチ, ヨー] (度数法)
rotation = R.from_euler('xyz', euler_angles, degrees=True)
quaternion = rotation.as_quat()  # [x, y, z, w] 形式

euler, quaternion


(array([0., 0., 0.]), array([0.19134172, 0.46193977, 0.19134172, 0.8446232 ]))

/mavros/local_position/pose

In [13]:
quaternion = [0.0032078074082483865, -0.0007461061350673449, 0.048003329729001815, -0.998841746039979]
rotation = R.from_quat(quaternion)
euler = rotation.as_euler('xyz', degrees=True)

print(euler)


[-0.37126891  0.06775302 -5.50314056]


/mavros/vision_pose/pose

In [12]:
quaternion = [-0.0012559330789372325, -0.0011566916946321726, 0.047968361526727676, -0.9988474249839783]
rotation = R.from_quat(quaternion)
euler = rotation.as_euler('xyz', degrees=True)

print(euler)

[ 0.13739591  0.13929804 -5.49872034]


rostopic echo /mavros/global_position/compass_hdg

data: 95.49
